version: "3.8"

services:
  frontend:
   container_name: app_frontend
   build: "./Front"
   ports:
      - 3001:3000

  backend:
    container_name: app_backend
    build: "./Back"
    ports:
      - 3002:3000
    depends_on:
      - database
    volumes: 
      - ./Back:/app
      - /app/node_modules
      
  database:
    container_name: db-app
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: examples
      MYSQL_TCP_PORT: 3307
      MYSQL_DATABASE: exampleDB
    ports:
      - 3307:3306
